version: "3.2"

networks:
  php_api_platform:

services:
  nginx_api:
    container_name: nginx_api
    image: nginx:stable-alpine
    ports:
      - "86:80"
    volumes:
      - ./app:/var/www/sf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_api
    networks:
      - php_api_platform

  php_api:
    container_name: php_api
    build:
      context: "./php/"
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/sf
      - ./php/conf/php.ini:/usr/local/etc/php/php.ini-production
    networks:
      - php_api_platform

